POST http://localhost:3000/reports
content-type: application/json

{
  "make": "vw",
  "model": "gol",
  "year": 1970,
  "mileage": 2000,
  "lat": 0,
  "lng": 0,
  "price": 7500
}

### Approve an existing report
PATCH  http://localhost:3000/reports/1
content-type: application/json

{
  "approved": true
}